global_workspace:
    latent_dim: 10

    representation_loss_coefficients:
        cycles: 1.0
        contrastives: 0.01
        demi_cycles: 1.0
        translations: 1.0
    loss_coefficients:
        representation_loss: 1.0
        add_loss: 1.0
        sub_loss: 1.0
        rotate_loss: 1.0
        task_loss: 1.0
    encoders:
        hidden_dim:
            image: 256
            digit: 256
            operation: 256
        n_layers: 2

    decoders:
        hidden_dim:
            image: 256
            digit: 256
        n_layers: 2

training:
    optim:
        lr: 0.001

    max_steps: 1000
    devices: 1
    batch_size: 1024
